config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'contribuicoes#index'

  resources :planos, only: [:new, :create]

  get 'contribuicoes/new/:plano', to: 'contribuicoes#new', as: 'new_contribuicao'
  resources :contribuicoes, only: [:index, :create, :show, :destroy]
  get 'contribuicoes/atualizar_cartao/:contribuicao', to: 'contribuicoes#atualizar_cartao', as: 'atualizar_cartao'
  post 'contribuicoes/atualizar_cartao', to: 'contribuicoes#update_cartao', as: 'update_cartao'

  resources :enderecos, only: [:new, :create, :edit, :update]

  resources :telefones, only: [:new, :create, :edit, :update]

  post 'pre_cadastro', to: 'pre_cadastros#show', as: 'pre_cadastro'

  get 'paginas/home'

  devise_scope :usuario do
    get     'login',      to: 'devise/sessions#new'
    get     'cadastro',   to: 'devise/registrations#new'
    get     'logout',     to: 'usuarios/sessions#destroy'
    delete  'logout',     to: 'usuarios/sessions#destroy'
  end

  devise_for :usuarios, path_names: { sign_in: 'login',
                                      sign_out: 'logout',
                                      sign_up: 'cadastro',
                                      edit: 'meus-dados' },
                        controllers: { registrations: 'usuarios/registrations',
                                       sessions: 'usuarios/sessions' }

end

app/views/partials/_flash.html.slim
/ Available flashs:
  :success, :info, :notice(:info) :warning, :danger, :error(:danger), :alert (:danger)
- flash.each do |key, value|  
  - key = 'danger' if key == 'error'
  - key = 'danger' if key == 'alert'
  - key = 'info' if key == 'notice'
  div[class="alert alert-#{key}"]
    .container
      = value.html_safe

app/views/partials/_footer.html.slim
footer.footer
  .container        
    .copyright.float-right
      | Powered by 
      a[href='https://github.com/jairbj/convinet' target='_blank']
        |CONVINET

app/views/partials/_navbar.html.slim
nav#sectionsNav.navbar.navbar-transparent.navbar-color-on-scroll.fixed-top.navbar-expand-lg[color-on-scroll="100"]  
  .container
    .navbar-translate
      .navbar-brand
        = link_to root_path
          = Rails.configuration.convinet['titulo']      
      button.navbar-toggler[type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation"]
        span.sr-only
          |Toggle navigation
        span.navbar-toggler-icon
        span.navbar-toggler-icon
        span.navbar-toggler-icon
    .collapse.navbar-collapse
      ul.navbar-nav.ml-auto      
        - if usuario_signed_in?
          li.nav-item
            = link_to contribuicoes_path, class: 'nav-link'
              i.material-icons
                |how_to_vote
              | Minhas Contibuições
          li.nav-item
            = link_to edit_usuario_registration_path, class: 'nav-link'
              i.material-icons
                |assignment_ind
              | Meus dados
          li.nav-item
            = link_to logout_path, method: :delete, class: 'nav-link'
              i.material-icons
                |exit_to_app
              | Sair
        - else
          li.nav-item
            = link_to root_path, class: 'nav-link'
              i.material-icons
                |home
              | Página Inicial