config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'contribuicoes#index'

  resources :planos, only: [:new, :create]

  get 'contribuicoes/new/:plano', to: 'contribuicoes#new', as: 'new_contribuicao'
  resources :contribuicoes, only: [:index, :create, :show, :destroy]
  get 'contribuicoes/atualizar_cartao/:contribuicao', to: 'contribuicoes#atualizar_cartao', as: 'atualizar_cartao'
  post 'contribuicoes/atualizar_cartao', to: 'contribuicoes#update_cartao', as: 'update_cartao'

  resources :enderecos, only: [:new, :create, :edit, :update]

  resources :telefones, only: [:new, :create, :edit, :update]

  post 'pre_cadastro', to: 'pre_cadastros#show', as: 'pre_cadastro'

  get 'paginas/home'

  devise_scope :usuario do
    get     'login',      to: 'devise/sessions#new'
    get     'cadastro',   to: 'devise/registrations#new'
    get     'logout',     to: 'usuarios/sessions#destroy'
    delete  'logout',     to: 'usuarios/sessions#destroy'
  end

  devise_for :usuarios, path_names: { sign_in: 'login',
                                      sign_out: 'logout',
                                      sign_up: 'cadastro',
                                      edit: 'meus-dados' },
                        controllers: { registrations: 'usuarios/registrations',
                                       sessions: 'usuarios/sessions' }

end

app/controllers/contribuicoes_controller.rb
class ContribuicoesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :checa_telefone
  before_action :checa_endereco

  def index
    @contribuicoes = current_usuario.contribuicoes.order 'id desc'
  end

  def new
    @contribuicao = current_usuario.contribuicoes.new
    @contribuicao.plano = Plano.find(params[:plano]);

    @session = PagSeguro::Session.create.id
  end

  def show
    @contribuicao = current_usuario.contribuicoes.find(params[:id])

    unless @contribuicao.check_status
      flash[:danger] = 'Erro ao conectar ao PagSeguro. Por favor tente novamente. COD: #05'
      redirect_to contribuicoes_path
      return
    end
  end

  def create
    @contribuicao = current_usuario.contribuicoes.new(contribuicao_params)
    @contribuicao.plano = Plano.find(params[:contribuicao][:plano]);

    unless @contribuicao.valid?
      flash[:danger] = 'Erro ao processar sua contribuição. Por favor tente novamente. COD: #03'
      redirect_to new_contribuicao_path(plano: @contribuicao.plano.id)
      return
    end

    subscription = gera_subscription(@contribuicao)

    subscription.credentials = PagSeguro::AccountCredentials.new(PagSeguro.email, PagSeguro.token)
    begin
      subscription.create
    rescue
      if recupera_contribuicao(@contribuicao.usuario, true)
        flash[:info] = 'Houve um erro na comunicação com o PagSeguro. 
                        Verifique abaixo se sua contribuição foi cadastrada.
                        Antes de tentar novamente, 
                        verifique a fatura do seu cartão de crédito 
                        e se já foi debitado, entre em contato com algum 
                        responsável pelo projeto.'
      else
        flash[:danger] = 'Erro ao processar sua contribuição. 
                          Antes de tentar novamente, 
                          verifique a fatura do seu cartão de crédito 
                          e se já foi debitado, entre em contato com algum 
                          responsável pelo projeto.'
      end
      redirect_to root_path
      return
    end

    if subscription.errors.any?
      puts 'PAGSEGURO -> ERRO CRIAR CONTRIBUIÇÃO'
      puts subscription.errors.join('\n')
      flash[:danger] = 'Erro ao processar sua contribuição. Por favor tente novamente. COD: #04'
      redirect_to new_contribuicao_path(plano: @contribuicao.plano.id)
      return
    end

    @contribuicao.codigo = subscription.code
    @contribuicao.save

    flash[:success] = 'Contribuição cadastrada com sucesso.'

    redirect_to root_path
  end

  def destroy
    @contribuicao = current_usuario.contribuicoes.find(params[:id])

    if @contribuicao.payment_cancel
      flash[:success] = 'Contribuição cancelada com sucesso.'
    else
      flash[:error] = 'Houve um erro ao efetuar o cancelamento da sua contribuição. Por favor tente novamente'
    end

    redirect_to @contribuicao
  end

  def atualizar_cartao
    @contribuicao = current_usuario.contribuicoes.find params[:contribuicao]
    @session = PagSeguro::Session.create.id
  end

  def update_cartao
    @contribuicao = current_usuario.contribuicoes.find(params[:contribuicao][:contribuicao])    
    @contribuicao.hash_cliente = params[:contribuicao][:hash_cliente]
    @contribuicao.token_cartao = params[:contribuicao][:token_cartao]
    @contribuicao.nome_cartao = params[:contribuicao][:nome_cartao]

    changePayment = gera_subscription_change_payment(@contribuicao)
    changePayment.credentials = PagSeguro::AccountCredentials.new(PagSeguro.email, PagSeguro.token)
    begin
      changePayment.update
    rescue
      flash[:danger] = 'Erro ao processar atualização do cartão de crédito junto ao PagSeguro, por favor tente novamente.'
      redirect_to atualizar_cartao_path(contribuicao: @contribuicao.id)
      return
    end

    if changePayment.errors.any? 
      flash[:error] = 'Erro ao atualizar cartão de crédito junto ao PagSeguro, por favor tente novamente.'
      redirect_to atualizar_cartao_path(contribuicao: @contribuicao.id)
      puts 'PAGSEGURO -> ERRO ATUALIZAR CARTÃO'
      puts changePayment.errors.join('\n')
    else
      flash[:success] = 'Cartão de crédito atualizado com sucesso.'
      redirect_to @contribuicao
    end
  end

  private

  def contribuicao_params
    params.require(:contribuicao).permit(:hash_cliente,
                                         :token_cartao,
                                         :nome_cartao)
  end

  def checa_telefone
    unless current_usuario.telefone
      flash[:info] = 'Antes de contribuir é necessário cadastrar seu telefone.'
      redirect_to :new_telefone
    end
  end

  def checa_endereco
    unless current_usuario.endereco
      flash[:info] = 'Antes de contribuir é necessário cadastrar seu endereço.'
      redirect_to :new_endereco
    end
  end


  def recupera_contribuicao(usuario, aguarda = false)
    sleep 5 if aguarda

    credentials = PagSeguro::AccountCredentials.new(PagSeguro.email, PagSeguro.token)

    if PagSeguro.environment == :sandbox
      email = "user#{usuario.id}@sandbox.pagseguro.com.br"
    else
      email = usuario.email
    end

    options = {
      credentials: credentials,      
      starts_at: Time.now.in_time_zone('Brasilia') - 15.minutes,
      ends_at: Time.now.in_time_zone('Brasilia'),
      sender_email: email
    }

    begin
      report = PagSeguro::Subscription.search_by_date_interval(options)
    rescue
      return false
    end

    unless report.valid?
      puts "PAGSEGURO: Erro recuperar contribuicao"
      puts report.errors.join("\n")
      puts options
      return false
    end

    contribuicoes_recuperadas = 0

    while report.next_page?
      report.next_page!
      report.subscriptions.each do |s|
        unless usuario.contribuicoes.find_by codigo: s.code
          plano = Plano.find_by nome: s.name
          if plano
            c = usuario.contribuicoes.new
            c.codigo = s.code
            c.atualizar_status(s.status)
            c.plano = plano
            contribuicoes_recuperadas += 1 if c.save
          end
        end
      end
    end

    return false unless contribuicoes_recuperadas
    contribuicoes_recuperadas
  end

  def gera_subscription_change_payment(contribuicao)
    if PagSeguro.environment == :sandbox
      email = "user#{contribuicao.usuario.id}@sandbox.pagseguro.com.br"
    else
      email = contribuicao.usuario.email
    end

    PagSeguro::SubscriptionChangePayment.new(
      subscription_code: contribuicao.codigo,
      sender: {
        name: contribuicao.usuario.nome,
        email: email,
        hash: contribuicao.hash_cliente,
        phone: {
          area_code: contribuicao.usuario.telefone.ddd,
          number: contribuicao.usuario.telefone.numero
        },
        document: { 
          type: 'CPF', 
          value: contribuicao.usuario.cpf 
        },
        address: {
          street: contribuicao.usuario.endereco.rua,
          number: contribuicao.usuario.endereco.numero,
          complement: contribuicao.usuario.endereco.complemento,
          district: contribuicao.usuario.endereco.bairro,
          city: contribuicao.usuario.endereco.cidade,
          state: contribuicao.usuario.endereco.estado,
          country: 'BRA',
          postal_code: contribuicao.usuario.endereco.cep
        }
      },
      subscription_payment_method: {
        token: contribuicao.token_cartao,
        holder: {
          name: contribuicao.nome_cartao,
          birth_date: contribuicao.usuario.nascimento,
          phone: {
            area_code: contribuicao.usuario.telefone.ddd,
            number: contribuicao.usuario.telefone.numero
          },
          document: {
            type: 'CPF',
            value: contribuicao.usuario.cpf
          },
          billing_address: {
            street: contribuicao.usuario.endereco.rua,
            number: contribuicao.usuario.endereco.numero,
            complement: contribuicao.usuario.endereco.complemento,
            district: contribuicao.usuario.endereco.bairro,
            city: contribuicao.usuario.endereco.cidade,
            state: contribuicao.usuario.endereco.estado,
            country: 'BRA',
            postal_code: contribuicao.usuario.endereco.cep
          },
        }
      }
    )
  end

  def gera_subscription(contribuicao)
    if PagSeguro.environment == :sandbox
      email = "user#{contribuicao.usuario.id}@sandbox.pagseguro.com.br"
    else
      email = contribuicao.usuario.email
    end
    PagSeguro::Subscription.new(
      plan: contribuicao.plano.codigo,
      sender: {
        name: contribuicao.usuario.nome,
        email: email,
        hash: contribuicao.hash_cliente,
        phone: {
          area_code: contribuicao.usuario.telefone.ddd,
          number: contribuicao.usuario.telefone.numero
        },
        document: {
          type: 'CPF',
          value: contribuicao.usuario.cpf
        },
        address: {
          street: contribuicao.usuario.endereco.rua,
          number: contribuicao.usuario.endereco.numero,
          complement: contribuicao.usuario.endereco.complemento,
          district: contribuicao.usuario.endereco.bairro,
          city: contribuicao.usuario.endereco.cidade,
          state: contribuicao.usuario.endereco.estado,
          country: 'BRA',
          postal_code: contribuicao.usuario.endereco.cep
        }
      },
      payment_method: {
        token: contribuicao.token_cartao,
        holder: {
          name: contribuicao.nome_cartao,
          birth_date: contribuicao.usuario.nascimento,
          document: {
            type: 'CPF',
            value: contribuicao.usuario.cpf
          },
          billing_address: {
            street: contribuicao.usuario.endereco.rua,
            number: contribuicao.usuario.endereco.numero,
            complement: contribuicao.usuario.endereco.complemento,
            district: contribuicao.usuario.endereco.bairro,

app/helpers/contribuicoes_helper.rb
module ContribuicoesHelper
end

app/views/contribuicoes/atualizar_cartao.html.slim
== content_for(:page_javascripts)
  - if PagSeguro.environment == :sandbox
    = javascript_include_tag('https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js')
  - else
    = javascript_include_tag('https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js')
  = javascript_include_tag('contribuicoes-bundle')

.container  
  .row
    .col-lg-6.col-md-6.ml-auto.mr-auto
      .card
        .card-header.card-header-primary.text-center
          h4.card-title
            | Atualizar cartão de crédito
        .card-body
          h3.text-center
            |Valor mensal: R$
            =< @contribuicao.plano.valor.to_i
            |,00
          p.description.text-center.margin-10
            | Informe abaixo os dados do novo cartão de crédito
            br
            strong
              |ATENÇÃO
            br
            |Você só poderá usar cartões de crédito vinculados ao seu CPF
          .pagamento-normal
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-credit-card                      
              = text_field :cartao, :nome, autofocus: true, autocomplete: "off", placeholder: "Nome como consta no cartão...", class: "form-control", maxlength: 50
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-credit-card                      
              = text_field :cartao, :numero, autofocus: true, autocomplete: "off", placeholder: "Número do cartão (sem espaços)...", class: "form-control", maxlength: 16
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-credit-card                                       
              = text_field :cartao, :cvv, autofocus: true, autocomplete: "off", placeholder: "Código de segurança CVV...", class: "form-control", maxlength: 4
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-calendar
              = text_field :cartao, :mes, autofocus: true, autocomplete: "off", placeholder: "Validade - Mês (MM)...", class: "form-control", maxlength: 2
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-calendar                                      
              = text_field :cartao, :ano, autofocus: true, autocomplete: "off", placeholder: "Validade - Ano (AA)...", class: "form-control", maxlength: 2
        .container.pagamento-normal
          = form_for @contribuicao, url: update_cartao_path, method: :post, html: {id: 'new_contribuicao', class: 'form'} do |f|
            = f.hidden_field :session, value: @session
            = f.hidden_field :contribuicao, value: @contribuicao.id
            = f.hidden_field :hash_cliente
            = f.hidden_field :token_cartao
            = f.hidden_field :nome_cartao
          .text-center
            button.btn.btn-primary.btn-round[onclick='processaContribuicao();' id='processar']
              |Atualizar cartão de crédito

app/views/contribuicoes/index.html.slim
.container  
  .row
    .col-lg-7.col-md-6.ml-auto.mr-auto
      .card      
        .card-header.card-header-primary.text-center
          h4.card-title
            |Minhas contribuições        
        .card-body
          - if @contribuicoes.any?
            .text-center                            
              = link_to :new_plano, class: 'btn btn-primary'
                |Fazer nova contribuição mensal              
            .text-center
              h4
                |Contribuições mensais
            .text-center
              table.tabela-contribuicoes
                thead.border-bottom
                  tr
                    td.border-right
                      h4
                        |Valor mensal
                    td.border-right
                      h4
                        |Status
                    td
                      h4
                        |Data de Início
                tbody
                  - @contribuicoes.each do |c|
                    tr
                      td.border-right
                        = link_to c
                          |R$
                          =< c.plano.valor.to_i
                          |,00
                      td.border-right
                        = link_to c
                          = c.status.to_s.capitalize
                      td
                        = c.created_at.to_date
          - else            
            .text-center            
              h3
                |Nenhuma contribuição mensal até o momento.              
              = link_to :new_plano, class: 'btn btn-primary'
                |Fazer nova contribuição mensal
            

app/views/contribuicoes/new.html.slim
== content_for(:page_javascripts)
  - if PagSeguro.environment == :sandbox
    = javascript_include_tag('https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js')
  - else
    = javascript_include_tag('https://stc.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.directpayment.js')
  = javascript_include_tag('contribuicoes-bundle')

.container  
  .row
    .col-lg-6.col-md-6.ml-auto.mr-auto
      .card
        .card-header.card-header-primary.text-center
          h4.card-title
            | Contribuição Mensal                      
        .card-body
          h3.text-center
            |Valor mensal: R$
            =< @contribuicao.plano.valor.to_i
            |,00
          p.description.text-center.margin-10
            | Informe abaixo os dados do cartão de crédito
            br
            strong
              |ATENÇÃO
            br
            |Você só poderá usar cartões de crédito vinculados ao seu CPF
          .pagamento-normal
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-credit-card                      
              = text_field :cartao, :nome, autofocus: true, autocomplete: "off", placeholder: "Nome como consta no cartão...", class: "form-control", maxlength: 50
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-credit-card                      
              = text_field :cartao, :numero, autofocus: true, autocomplete: "off", placeholder: "Número do cartão (sem espaços)...", class: "form-control", maxlength: 16
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-credit-card                                       
              = text_field :cartao, :cvv, autofocus: true, autocomplete: "off", placeholder: "Código de segurança CVV...", class: "form-control", maxlength: 4
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-calendar
              = text_field :cartao, :mes, autofocus: true, autocomplete: "off", placeholder: "Validade - Mês (MM)...", class: "form-control", maxlength: 2
            .input-group
              .input-group-prepend
                span.input-group-text
                  i.fa.fa-calendar                                      
              = text_field :cartao, :ano, autofocus: true, autocomplete: "off", placeholder: "Validade - Ano (AA)...", class: "form-control", maxlength: 2
        .container.pagamento-normal
          = form_for @contribuicao, html: {class: 'form'} do |f|
            = hidden_field :contribuicao, :session, value: @session
            = f.hidden_field :plano, value: @contribuicao.plano.id
            = f.hidden_field :hash_cliente
            = f.hidden_field :token_cartao
            = f.hidden_field :nome_cartao
          .text-center
            button.btn.btn-primary.btn-round[onclick='processaContribuicao();' id='processar']
              |Fazer contribuição
          br
        .container#texto-pagseguro-alternativo
          .text-center
            |Se a sua contribuição está sendo cancelada automaticamente após o pagamento, clique
            =<>link_to 'javascript:pagamentoAlternativo();'
              |AQUI
            |para utilizar um método de pagamento alternativo.
        .container#bt-pagseguro-alternativo
          .text-center
            h3
              |Instruções:
          .text-center
            |Clique no botão abaixo para efetuar seu pagamento direto no site do PagSeguro. 
          .text-center
            |Na tela que irá se abrir, escolha a opção "Comprar sem cadastro" e utilize o mesmo e-mail que você usou no nosso cadastro.
          .text-center
            |Dentro de 30 minutos após efetuar o pagamento, sua contribuição constará em nosso sistema.
          br
          .text-center
            '<!-- INICIO FORMULARIO BOTAO PAGSEGURO: NAO EDITE OS COMANDOS DAS LINHAS ABAIXO -->
            form[action='https://pagseguro.uol.com.br/pre-approvals/request.html' method='post']
              input[type='hidden' name='code' value="#{@contribuicao.plano.codigo}"]
              input[type='hidden' name='iot' value='button']
              input[type='image' src='https://stc.pagseguro.uol.com.br/public/img/botoes/assinaturas/209x48-assinar-assina.gif' name='submit' alt='Pague com PagSeguro - É rápido, grátis e seguro!' width='209' height='48']
            '<!-- FINAL FORMULARIO BOTAO PAGSEGURO -->

app/views/contribuicoes/show.html.slim
.container  
  .row
    .col-lg-7.col-md-6.ml-auto.mr-auto
      .card      
        .card-header.card-header-primary.text-center
          h4.card-title
            |Minha contribuição        
        .card-body
          h3.text-center
            |Valor mensal: R$
            =< @contribuicao.plano.valor.to_i
            |,00
          h4.text-center
            |Status: 
            = @contribuicao.status.to_s.capitalize
          br
          h4.text-center
            |Pagamentos
          .text-center
              table.tabela-contribuicoes
                thead.border-bottom
                  tr
                    td.border-right
                      h4
                        |Data da contribuição
                    td
                      h4
                        |Status
                tbody
                  - @contribuicao.pagamentos.each do |p|
                    tr
                      td.border-right
                        = p.scheduling_date
                      td                        
                        = status_pagamento_texto(p.status)
          - unless @contribuicao.cancelado?
            br
            .container
              .text-center
                = link_to atualizar_cartao_path(contribuicao: @contribuicao.id), class: 'btn btn-primary'
                    |Atualizar cartão de crédito              
              .text-center
                = link_to @contribuicao, class: 'btn btn-primary', data: { confirm: 'Tem certeza que deseja cancelar sua contribuição?' }, method: :delete
                    |Cancelar Contribuição              